spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newsdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      table-prefix: news_
      #\u8BBE\u7F6E\u5168\u5C40\u4E3B\u952E\u81EA\u589E
      id-type: auto
      #mybatis\u90A3\u4E2A\u522B\u540D\u53EF\u80FDmybatis\u4E0D\u80FD\u4F7F\u7528\u518D\u914D\u7F6E\u4E00\u4E2A
  type-enums-package: com.mybatis.enums
  type-aliases-package: com.mybatis.bean
